# -*- coding: utf-8 -*-
import io

EDITS = {
    "audit/dso_facts_batch1.py": [
        (521, "It was discovered by Giovanni Hodierna before 1654.",
              "Giovanni Hodierna recorded M37 before 1654, long before Messier's catalog."),
    ],
    "audit/dso_facts_batch2.py": [
        (72, "The galaxy hosts a supermassive black hole at its center.",
             "M49 hides a supermassive black hole in its core, among the heaviest in the Virgo Cluster."),
    ],
    "audit/dso_facts_batch3.py": [
        (248, "The cluster is about 100 million years old.",
              "The stars of M93 are roughly 100 million years old."),
        (440, "The galaxy hosts a supermassive black hole at its center.",
              "M105's central supermassive black hole is revealed by the rapid motion of stars around it."),
    ],
    "audit/dso_facts_batch4.py": [
        (71, "The cluster was discovered by William Herschel in 1787.",
             "William Herschel discovered NGC 559, the C8 cluster, in 1787."),
    ],
    "audit/dso_facts_batch5.py": [
        (56,  "NGC 1528 is about 370 million years old.",
              "The age of NGC 1528 is about 370 million years."),
        (87,  "The cluster was discovered by William Herschel in 1784.",
              "William Herschel discovered NGC 1647 in 1784."),
        (104, "NGC 1817 is about 400 million years old.",
              "NGC 1817 is roughly 400 million years old, a middle-aged open cluster."),
        (185, "The cluster was discovered by William Herschel in 1784.",
              "Herschel recorded NGC 2169 in 1784, naming it for its '37' pattern."),
        (263, "The cluster was discovered by William Herschel in 1785.",
              "Herschel first observed NGC 2301 in 1785, noting its line of bright stars."),
        (294, "It shines at magnitude 7.2 and contains about 100 stars.",
              "Caroline's Cluster shines at magnitude 7.2 with about 100 stars."),
        (408, "NGC 2477 was discovered by Nicolas-Louis de Lacaille in 1751.",
              "Nicolas-Louis de Lacaille discovered NGC 2477 in 1751 from the Cape of Good Hope."),
        (471, "The cluster was discovered by William Herschel in 1785.",
              "William Herschel discovered NGC 2539 in 1785 while surveying Puppis."),
        (472, "NGC 2539 is about 370 million years old.",
              "NGC 2539 has an age of roughly 370 million years."),
        (488, "NGC 2547 was discovered by Nicolas-Louis de Lacaille in 1751.",
              "Lacaille recorded NGC 2547 in 1751 during his southern constellation survey."),
        (505, "It was discovered by James Dunlop in 1826.",
              "Dunlop first recorded NGC 55 in 1826 during his survey of the southern sky."),
        (553, "NGC 300 was discovered by James Dunlop in 1826.",
              "James Dunlop discovered NGC 300 in 1826 while sweeping Sculptor."),
        (568, "NGC 3114 was discovered by James Dunlop in 1826.",
              "Dunlop recorded the wide cluster NGC 3114 in 1826 from Australia."),
    ],
    "audit/dso_facts_batch6.py": [
        (105, "The cluster is young, only about 10 million years old.",
              "The Jewel Box is only about 10 million years old, a newborn cluster."),
        (153, "It was discovered by James Dunlop in 1826.",
              "James Dunlop discovered NGC 2808 in 1826 from his observatory in Australia."),
        (169, "The cluster is about 100 million years old.",
              "NGC 6025 is around 100 million years old, a young cluster in Triangulum Australe."),
        (184, "NGC 6067 is about 100 million years old.",
              "The stars of NGC 6067 are about 100 million years old."),
        (200, "NGC 6087 was discovered by James Dunlop in 1826.",
              "James Dunlop discovered NGC 6087 in 1826 among the clusters of Norma."),
        (216, "NGC 6124 was discovered by Nicolas-Louis de Lacaille in 1751.",
              "The cluster NGC 6124 was first cataloged by Lacaille in 1751."),
        (233, "It was discovered by Giovanni Hodierna before 1654.",
              "Hodierna cataloged NGC 6231 before 1654, making it one of the earliest recorded open clusters."),
        (295, "NGC 6397 is one of the nearest globular clusters to Earth.",
              "NGC 6397 is one of the nearest globular clusters, at only about 7,800 light-years."),
        (312, "NGC 6572 was discovered by William Herschel in 1784.",
              "Herschel discovered NGC 6572 in 1784 and described it as a vivid green disk."),
        (359, "NGC 6752 is one of the nearest globular clusters to Earth.",
              "NGC 6752 is one of the closest globular clusters to the Sun."),
        (361, "It was discovered by James Dunlop in 1826.",
              "James Dunlop cataloged NGC 6752 in 1826."),
        (375, "The cluster was discovered by William Herschel in 1785.",
              "Herschel cataloged NGC 6755 in 1785 during his Milky Way sweeps."),
        (392, "NGC 6781 was discovered by William Herschel in 1788.",
              "Herschel discovered NGC 6781 in 1788, a faint ring of gas in Aquila."),
    ],
    "audit/dso_facts_batch7.py": [
        (9,   "The cluster was discovered by Caroline Herschel in 1783.",
              "Caroline Herschel discovered NGC 6819 in 1783."),
        (39,  "The cluster was discovered by Caroline Herschel in 1783.",
              "Caroline Herschel found NGC 6866 in 1783 during her comet searches."),
        (56,  "NGC 6884 was discovered by Ralph Copeland in 1884.",
              "Ralph Copeland discovered NGC 6884 in 1884 during his nebula observations."),
        (72,  "NGC 6891 was discovered by Ralph Copeland in 1884.",
              "Copeland found NGC 6891 in 1884 while surveying Delphinus."),
        (136, "NGC 6940 was discovered by William Herschel in 1784.",
              "William Herschel discovered NGC 6940 in 1784 among the stars of Vulpecula."),
        (150, "It lies about 2,400 light-years away and shines at magnitude 7.0.",
              "The Western Veil lies about 2,400 light-years away and glows at magnitude 7.0."),
        (166, "It lies about 2,400 light-years away and shines at magnitude 7.0.",
              "The Eastern Veil sits about 2,400 light-years away at magnitude 7.0."),
        (231, "The cluster was discovered by William Herschel in 1788.",
              "William Herschel discovered NGC 7062 in 1788."),
        (232, "NGC 7062 is about 400 million years old.",
              "The age of NGC 7062 is estimated at about 400 million years."),
        (247, "The cluster was discovered by William Herschel in 1788.",
              "Herschel logged NGC 7063 in 1788 while sweeping Cygnus."),
        (248, "NGC 7063 is about 100 million years old.",
              "NGC 7063 is a young cluster aged about 100 million years."),
        (280, "NGC 7139 was discovered by William Herschel in 1787.",
              "William Herschel found NGC 7139 in 1787 during his sweeps of the northern sky."),
        (295, "The cluster is young, only about 10 million years old.",
              "NGC 7160 is a very young cluster, just 10 million years old."),
        (296, "NGC 7160 was discovered by William Herschel in 1787.",
              "Herschel recorded NGC 7160 in 1787 while mapping the clusters of Cepheus."),
        (311, "The cluster was discovered by William Herschel in 1787.",
              "Herschel recorded NGC 7209 in 1787 while exploring the small constellation Lacerta."),
        (312, "NGC 7209 is about 400 million years old.",
              "The stars of NGC 7209 are about 400 million years old."),
        (344, "NGC 7354 was discovered by William Herschel in 1787.",
              "William Herschel cataloged NGC 7354 in 1787, noting its small round form."),
        (358, "It shines at magnitude 7.2 and contains about 100 stars.",
              "NGC 7380 glows at magnitude 7.2 and holds about 100 stars."),
        (375, "The cluster is young, only about 10 million years old.",
              "The stars of NGC 7510 are only 10 million years old."),
        (376, "NGC 7510 was discovered by William Herschel in 1787.",
              "Herschel logged NGC 7510 in 1787 as a compact grouping in Cepheus."),
        (392, "NGC 7686 was discovered by William Herschel in 1787.",
              "William Herschel discovered NGC 7686 in 1787 among the star fields of Andromeda."),
        (424, "NGC 7790 was discovered by William Herschel in 1788.",
              "William Herschel discovered NGC 7790 in 1788 in Cassiopeia."),
    ],
}

for path, edits in EDITS.items():
    lines = io.open(path, encoding="utf-8").read().split("\n")
    for lineno, old, new in sorted(edits, key=lambda e: -e[0]):
        cur = lines[lineno - 1]
        if old not in cur:
            print("MISMATCH %s:%d expected %r got %r" % (path, lineno, old, cur))
        lines[lineno - 1] = cur.replace(old, new)
    io.open(path, "w", encoding="utf-8").write("\n".join(lines))

print("edits applied")
