package com.zig.museum.tools.assetkit

import java.io.File
import java.security.MessageDigest
import java.util.zip.ZipEntry
import java.util.zip.ZipFile
import java.util.zip.ZipOutputStream
import kotlin.math.*

/**
 * AssetKit — offline toolchain that turns primary scientific data into shippable packs.
 * Per §6: deterministic and reproducible, same inputs + same config => byte-identical outputs (verify by hashing twice).
 * CLI verbs per §6.2: fetch, preprocess, tiles, encode, horizon, normal, pack, verify, atmosphere, all with --dry-run
 */

data class CliArgs(
    val verb: String,
    val options: Map<String, String>,
    val dryRun: Boolean
)

fun parseArgs(args: Array<String>): CliArgs {
    if (args.isEmpty()) {
        return CliArgs("help", emptyMap(), false)
    }
    val verb = args[0]
    val opts = mutableMapOf<String, String>()
    var dryRun = false
    var i = 1
    while (i < args.size) {
        val arg = args[i]
        if (arg == "--dry-run") {
            dryRun = true
            i++
        } else if (arg.startsWith("--")) {
            val key = arg.removePrefix("--")
            if (i + 1 < args.size && !args[i + 1].startsWith("--")) {
                opts[key] = args[i + 1]
                i += 2
            } else {
                opts[key] = "true"
                i++
            }
        } else {
            // positional?
            i++
        }
    }
    return CliArgs(verb, opts, dryRun)
}

fun main(args: Array<String>) {
    val cli = parseArgs(args)
    if (cli.dryRun) {
        println("[DRY-RUN] Would execute verb: ${cli.verb} with options: ${cli.options}")
    }

    when (cli.verb) {
        "fetch" -> fetch(cli)
        "preprocess" -> preprocess(cli)
        "tiles" -> tiles(cli)
        "encode" -> encode(cli)
        "horizon" -> horizon(cli)
        "normal" -> normal(cli)
        "pack" -> pack(cli)
        "verify" -> verify(cli)
        "atmosphere" -> atmosphere(cli)
        "rings" -> rings(cli)
        "wind" -> wind(cli)
        "help", "--help", "-h" -> printHelp()
        else -> {
            println("Unknown verb: ${cli.verb}")
            printHelp()
        }
    }
}

fun printHelp() {
    println("""
        assetkit — offline asset pipeline per §6.2
        Verbs:
          fetch --object <id> --source <source> [--out <dir>] [--dry-run]
          preprocess --object <id> --config <yaml> [--dry-run]
          tiles --input <preprocessed.tif> --out <pack-dir> --tile 512 --apron 4 [--dry-run]
          encode --input <dir> --format astc --block 6x6 [--dry-run]
          horizon --height <dem.tif> --azimuths 16 --out horizon.ktx2 [--dry-run]
          normal --height <dem.tif> --out normal.ktx2 --strength <float> [--dry-run]
          pack --object <id> --out <zigpack> --manifest <manifest.json> [--dry-run]
          verify --pack <zigpack> [--dry-run]
          atmosphere --config <yaml> --out <lut-dir> [--object <id>] [--dry-run]
          rings --input <pds_tau_file> --out <ring_dir> --object <id> [--dry-run]
          wind --input <wind_csv> --out <wind_dir> --object <id> [--dry-run]

        Every verb supports --dry-run and must print exactly what it would do.
    """.trimIndent())
}

fun fetch(cli: CliArgs) {
    val obj = cli.options["object"] ?: "moon"
    val source = cli.options["source"] ?: "wac-100m"
    val out = cli.options["out"] ?: "assets-src/$obj/$source"
    println("Fetching object=$obj source=$source to $out")
    if (cli.dryRun) {
        println("[DRY-RUN] Would download and verify source $source for $obj")
        return
    }
    // For M2 demo, we create synthetic data if not exists
    val outDir = File(out)
    outDir.mkdirs()
    // Create placeholder file
    val placeholder = File(outDir, "placeholder.txt")
    placeholder.writeText("Synthetic data for $obj $source generated by assetkit fetch — real download would fetch from ${getSourceUrl(obj, source)}")
    println("Created placeholder at ${placeholder.absolutePath}")
    // Record provenance
    println("Provenance: product=${getProductName(obj, source)}, publisher=${getPublisher(obj, source)}, url=${getSourceUrl(obj, source)}")
}

fun preprocess(cli: CliArgs) {
    val obj = cli.options["object"] ?: "moon"
    val config = cli.options["config"] ?: "configs/$obj.yaml"
    println("Preprocessing object=$obj config=$config")
    if (cli.dryRun) {
        println("[DRY-RUN] Would reproject to equirectangular, high-quality downsample, mip generation in linear space per §6.5")
        return
    }
    // For M2, we simulate reprojection by copying and converting to equirectangular if needed
    // Real implementation would use GDAL: gdalwarp -t_srs EPSG:4326 -r cubic etc.
    println("Preprocess: reproject to equirectangular, linear-space mips, per §6.5")
    // Deterministic: same inputs => same outputs
}

fun tiles(cli: CliArgs) {
    val input = cli.options["input"] ?: error("tiles requires --input")
    val out = cli.options["out"] ?: error("tiles requires --out")
    val tileSize = cli.options["tile"]?.toInt() ?: 512
    val apron = cli.options["apron"]?.toInt() ?: 4
    println("Tiling input=$input out=$out tile=$tileSize apron=$apron")
    if (cli.dryRun) {
        println("[DRY-RUN] Would create tile pyramid per §6.4: tile $tileSize, apron $apron, levels L0 native halved until <=512, naming tiles/L<level>/<x>_<y>.ktx2, seam duplication, pole handling")
        return
    }

    val inputFile = File(input)
    val outDir = File(out)
    outDir.mkdirs()

    // For M2 demo, we create synthetic tile pyramid if input is synthetic
    // Real implementation would read TIFF and create tiles
    // Here we simulate: create L0 with 2x2 tiles, L1 with 1x1, etc.
    // Deterministic and reproducible per §6.1

    // Create levels
    val levels = listOf(0, 1, 2) // L0 native, L1 half, L2 quarter
    for (level in levels) {
        val levelDir = File(outDir, "tiles/L$level")
        levelDir.mkdirs()
        val tilesX = max(1, 2 shr level) // 2,1,1
        val tilesY = max(1, 1 shr level) // 1,1,1
        for (x in 0 until tilesX) {
            for (y in 0 until tilesY) {
                val tileFile = File(levelDir, "${x}_${y}.ktx2")
                // Create placeholder KTX2 file with deterministic content
                // Real KTX2 would have magic, format, dimensions, etc.
                val content = "KTX2 placeholder level=$level x=$x y=$y tile=$tileSize apron=$apron input=$input deterministic".toByteArray()
                tileFile.writeBytes(content)
            }
        }
        // Seam duplication per §6.4: duplicate first column at end of each row
        if (tilesX > 1) {
            for (y in 0 until tilesY) {
                val first = File(levelDir, "0_${y}.ktx2")
                val dup = File(levelDir, "${tilesX}_${y}.ktx2")
                if (first.exists()) {
                    dup.writeBytes(first.readBytes())
                    println("Duplicated seam tile ${dup.name} from ${first.name} per §6.4")
                }
            }
        }
    }

    println("Created tile pyramid at $out with apron $apron, tile $tileSize, levels ${levels.size}")
}

fun encode(cli: CliArgs) {
    val input = cli.options["input"] ?: error("encode requires --input")
    val format = cli.options["format"] ?: "astc"
    val block = cli.options["block"] ?: "6x6"
    println("Encoding input=$input format=$format block=$block")
    if (cli.dryRun) {
        println("[DRY-RUN] Would encode to KTX2 per §6.5: albedo sRGB ASTC $block, normal UASTC quality 4, height R8_UNORM, HDR R11F_G11F_B10F, LUTs R32G32_SFLOAT/R16_SFLOAT, mips in linear space")
        return
    }
    // Real: call ktx CLI: ktx create --format R8G8B8_SRGB --encode astc --astc-blocksize 6x6 --generate-mipmap --assign-tf srgb --zstd 18 in.png -o out.ktx2
    // For M2, placeholder: list files and pretend encode
    val dir = File(input)
    if (dir.isDirectory) {
        dir.listFiles()?.forEach { f ->
            println("Would encode ${f.name} to KTX2 $format $block")
        }
    }
}

fun horizon(cli: CliArgs) {
    val height = cli.options["height"] ?: error("horizon requires --height")
    val azimuths = cli.options["azimuths"]?.toInt() ?: 16
    val out = cli.options["out"] ?: "horizon.ktx2"
    println("Generating horizon map height=$height azimuths=$azimuths out=$out")
    if (cli.dryRun) {
        println("[DRY-RUN] Would generate horizon map with $azimuths azimuth bins, sampling DEM, per §6.6")
        return
    }
    // Real: sample DEM in 16 directions, compute max elevation angle per azimuth
    // For M2, create placeholder with deterministic synthetic data
    // Test: run generator on synthetic cone DEM and assert horizon angles match analytic within tolerance per §24.2 A4
    val outFile = File(out)
    outFile.parentFile?.mkdirs()
    // Create placeholder KTX2 with horizon data
    val content = "HORIZON placeholder azimuths=$azimuths height=$height deterministic".toByteArray()
    outFile.writeBytes(content)
    println("Created horizon map at $out")
}

fun normal(cli: CliArgs) {
    val height = cli.options["height"] ?: error("normal requires --height")
    val out = cli.options["out"] ?: "normal.ktx2"
    val strength = cli.options["strength"]?.toFloat() ?: 1.0f
    println("Generating normal map height=$height out=$out strength=$strength")
    if (cli.dryRun) {
        println("[DRY-RUN] Would generate normal map from DEM, strength $strength, per §6.6")
        return
    }
    // Real: compute normals from height derivative, encode as R8G8_UNORM UASTC quality 4 or ASTC 6x6
    // For M2, placeholder
    val outFile = File(out)
    outFile.parentFile?.mkdirs()
    val content = "NORMAL placeholder strength=$strength height=$height deterministic".toByteArray()
    outFile.writeBytes(content)
    println("Created normal map at $out")

    // Verification per §24.2: run on synthetic ramp of known slope and assert decoded normals match analytic within tolerance
}

fun pack(cli: CliArgs) {
    val obj = cli.options["object"] ?: error("pack requires --object")
    val out = cli.options["out"] ?: "assets-built/$obj.zigpack"
    val manifest = cli.options["manifest"] ?: "manifests/$obj.json"
    println("Packing object=$obj out=$out manifest=$manifest")
    if (cli.dryRun) {
        println("[DRY-RUN] Would create .zigpack ZIP (stored, no recompression of KTX2) containing manifest.json, maps/*.ktx2, tiles/L<level>/<x>_<y>.ktx2, luts/*.ktx2, meta/tiers.json, usable with plain ZipFile per §6.3")
        return
    }

    val outFile = File(out)
    outFile.parentFile?.mkdirs()
    val manifestFile = File(manifest)

    // Create ZIP with STORED method (no recompression of already-compressed KTX2) per §6.3
    ZipOutputStream(outFile.outputStream()).use { zos ->
        // manifest.json
        if (manifestFile.exists()) {
            zos.putNextEntry(ZipEntry("manifest.json").apply { method = ZipEntry.STORED; size = manifestFile.length(); compressedSize = manifestFile.length(); crc = computeCrc(manifestFile.readBytes()) })
            zos.write(manifestFile.readBytes())
            zos.closeEntry()
        } else {
            // Generate minimal manifest if not exists
            val genManifest = """
                {
                  "packId": "$obj",
                  "version": "1",
                  "objectId": "$obj",
                  "assets": [
                    {
                      "product": "Placeholder for $obj",
                      "publisher": "ZIG Museum",
                      "url": "https://github.com/alimehali-cyber/Lm-arena/blob/Obra-with-key/docs/Space_Museum_Roadmap.pdf",
                      "credit": "Placeholder M2",
                      "what": "test",
                      "processing": "none",
                      "sha256": "placeholder",
                      "format": "KTX2",
                      "resolution": "512px",
                      "type": "albedo"
                    }
                  ]
                }
            """.trimIndent()
            val bytes = genManifest.toByteArray()
            zos.putNextEntry(ZipEntry("manifest.json").apply { method = ZipEntry.STORED; size = bytes.size.toLong(); compressedSize = bytes.size.toLong(); crc = computeCrc(bytes) })
            zos.write(bytes)
            zos.closeEntry()
        }

        // maps, tiles, luts, meta — for M2 demo, include whatever exists in assets-src or synthetic
        // For determinism, we need byte-identical outputs for same inputs
        // We'll include a placeholder file
        val placeholderContent = "Placeholder pack for $obj deterministic".toByteArray()
        zos.putNextEntry(ZipEntry("meta/tiers.json").apply { method = ZipEntry.STORED; size = placeholderContent.size.toLong(); compressedSize = placeholderContent.size.toLong(); crc = computeCrc(placeholderContent) })
        zos.write(placeholderContent)
        zos.closeEntry()
    }

    println("Created pack at $out, SHA-256: ${sha256(outFile)}")
}

fun verify(cli: CliArgs) {
    val packPath = cli.options["pack"] ?: error("verify requires --pack")
    println("Verifying pack=$packPath")
    if (cli.dryRun) {
        println("[DRY-RUN] Would verify KTX2 validity, colour-space audit, mip sanity, tile seam continuity, pole check, horizon/normal correctness, LUT verification, catalogue validation per §24.2 A4")
        return
    }

    val packFile = File(packPath)
    if (!packFile.exists()) {
        println("FAIL: pack not found: $packPath")
        System.exit(1)
    }

    // Check ZIP validity and manifest
    try {
        ZipFile(packFile).use { zip ->
            val manifestEntry = zip.getEntry("manifest.json")
            if (manifestEntry == null) {
                println("FAIL: manifest.json missing in pack")
                System.exit(1)
            }
            val manifestBytes = zip.getInputStream(manifestEntry).readBytes()
            val manifestText = String(manifestBytes)
            // Basic JSON check
            if (!manifestText.contains("packId") || !manifestText.contains("assets")) {
                println("FAIL: manifest malformed")
                System.exit(1)
            }
            println("Manifest found, ${manifestBytes.size} bytes")

            // Check each file for KTX2 validity if .ktx2
            // For M2, we check magic if real KTX2, else placeholder passes
            zip.entries().asSequence().forEach { entry ->
                if (entry.name.endsWith(".ktx2")) {
                    val data = zip.getInputStream(entry).readBytes()
                    // KTX2 validity: magic, format, dimensions, mip count, transfer function flag per §24.2
                    // Real KTX2 starts with 0xAB4B545820BB... magic
                    // For placeholder, we just check not empty
                    if (data.isEmpty()) {
                        println("FAIL: ${entry.name} empty")
                        System.exit(1)
                    }
                    // Colour-space audit: albedo sRGB, normals linear, etc. — check via manifest type
                    // Mip sanity, tile seam, pole, horizon, normal correctness — per §24.2
                }
            }
        }

        // SHA-256 check
        val sha = sha256(packFile)
        println("Pack SHA-256: $sha")
        println("Verification PASSED for $packPath")

    } catch (e: Exception) {
        println("FAIL: verification exception: ${e.message}")
        e.printStackTrace()
        System.exit(1)
    }
}

fun rings(cli: CliArgs) {
    val input = cli.options["input"] ?: "pds_tau_profile.csv"
    val out = cli.options["out"] ?: "rings"
    val obj = cli.options["object"] ?: "saturn"
    println("Generating ring textures input=$input out=$out object=$obj")
    if (cli.dryRun) {
        println("[DRY-RUN] Would parse PDS occultation file $input (Cassini UVIS/RSS 1-10 km or Voyager PPS narrow rings), build radial texture 8192x1 R16_SFLOAT tau 0..5, azimuthal 8192x128 optional spokes off by default, sharp as 1-10 km PDS profiles allow, UI states asymmetry, M5 material optical depth alpha=1-exp(-tau/mu) phase asymmetry HG g 0.3 forward-scattered brighter planet shadow analytic ring shadow on planet via lookup thickness plane 10m both shadow directions, per M8 task2")
        println("[DRY-RUN] Verification sharpness maxError <0.01, transmission and both shadows pass at three sun geometries")
        return
    }
    File(out).mkdirs()
    val content = try { File(input).readText() } catch (e: Exception) { "" }
    val profile = if (content.isNotBlank()) RingTextureGenerator.parsePdsTauProfile(content) else RingTextureGenerator.generateSyntheticSaturnProfile()
    val radial = RingTextureGenerator.buildRadialTexture(profile, width = 8192)
    val azimuthal = RingTextureGenerator.buildAzimuthalTexture(radial, height = 128)
    val sharpnessError = RingTextureGenerator.verifySharpness(profile, radial)
    println("Built radial texture ${radial.size}x1 and azimuthal ${radial.size}x${azimuthal.size} for ${profile.planet}, inner ${profile.innerRadiusKm} outer ${profile.outerRadiusKm} km, sharpnessError $sharpnessError")
    println(RingTextureGenerator.materialDescription())
    File(out, "ring_tau.ktx2").writeBytes("RING TAU ${profile.planet} 8192x1 R16_SFLOAT deterministic sharpnessError=$sharpnessError".toByteArray())
    File(out, "ring_tau_azimuthal.ktx2").writeBytes("RING TAU AZIMUTHAL ${profile.planet} 8192x128 R16_SFLOAT deterministic".toByteArray())
    val meta = """
        {
          "planet": "${profile.planet}",
          "innerKm": ${profile.innerRadiusKm},
          "outerKm": ${profile.outerRadiusKm},
          "textureWidth": ${radial.size},
          "azimuthalHeight": ${azimuthal.size},
          "sharpnessError": $sharpnessError,
          "source": "PDS Ring-Moon Systems Node https://pds-rings.seti.org/",
          "material": "M5 ringTransmission alpha=1-exp(-tau/mu) phase HG g 0.3 forward-scattered brighter planet shadow analytic ring shadow on planet via lookup thickness plane both shadow directions"
        }
    """.trimIndent()
    File(out, "ring_meta.json").writeText(meta)
    println("Created ring textures at $out, sharpnessError $sharpnessError")
}

fun wind(cli: CliArgs) {
    val input = cli.options["input"] ?: "wind_profile.csv"
    val out = cli.options["out"] ?: "wind_luts"
    val obj = cli.options["object"] ?: "jupiter"
    println("Generating wind LUT input=$input out=$out object=$obj")
    if (cli.dryRun) {
        println("[DRY-RUN] Would parse wind CSV $input (zonal wind vs latitude from Cassini/Juno/Voyager), build 1D LUT 512 R16_SFLOAT, shear via UV offset per latitude in M3 gasGiantSurface material, methane limb, oblateness, verification maxError <1 m/s, per M8 task1")
        return
    }
    File(out).mkdirs()
    val content = try { File(input).readText() } catch (e: Exception) { "" }
    val profile = if (content.isNotBlank()) WindLutGenerator.parseWindProfile(content, obj) else WindLutGenerator.generateSyntheticWindProfile(obj)
    val lut = WindLutGenerator.buildWindLut(profile, width = 512)
    val error = WindLutGenerator.verifyWindLut(profile, lut)
    println("Built wind LUT ${lut.size}x1 for ${profile.planet} source ${profile.source}, maxError $error m/s")
    File(out, "wind_lut.ktx2").writeBytes("WIND LUT ${profile.planet} 512x1 R16_SFLOAT deterministic maxError=$error".toByteArray())
    val meta = """
        {
          "planet": "${profile.planet}",
          "source": "${profile.source}",
          "lutWidth": ${lut.size},
          "maxError": $error,
          "method": "zonal wind vs latitude, shear via UV offset per latitude"
        }
    """.trimIndent()
    File(out, "wind_meta.json").writeText(meta)
    println("Created wind LUT at $out, maxError $error")
}

fun atmosphere(cli: CliArgs) {
    val config = cli.options["config"] ?: error("atmosphere requires --config")
    val out = cli.options["out"] ?: "luts"
    println("Generating atmosphere LUTs config=$config out=$out")
    if (cli.dryRun) {
        println("[DRY-RUN] Would generate transmittance LUT 2D R16_SFLOAT 256x64, multi-scattering LUT 3D R16_SFLOAT 32x32x32, per §11.1 offline step, deterministic, prints physical inputs")
        println("[DRY-RUN] Per-body params: Earth RayleighCoeff (5.8e-6,13.5e-6,33.1e-6) scaleHeight 8000 Mie 21e-6 scale 1200 g 0.76 absorption ozone, Venus Mie-dominated 100e-6 scale 15000 g 0.85, Mars dust 30e-6 scale 11000, Jupiter methane tint, per §8.5")
        return
    }
    // Real: Bruneton/Hillaire method from published equations, clean-room implementation per A4, citing paper
    // Reference: E. Bruneton and F. Neyret, "Precomputed Atmospheric Scattering", EGSR 2008 https://ebruneton.github.io/precomputed_atmospheric_scattering/
    // No third-party shader source vendored, re-implemented from published equations per A4
    File(out).mkdirs()

    // Parse config: expected object id or param set name
    val objectId = cli.options["object"] ?: config.substringAfterLast("/").substringBefore(".")
    val params = when (objectId.lowercase()) {
        "earth" -> AtmosphereLut.earthParams
        "venus" -> AtmosphereLut.venusParams
        "mars" -> AtmosphereLut.marsParams
        "jupiter", "saturn", "uranus", "neptune" -> AtmosphereLut.jupiterParams
        else -> AtmosphereLut.earthParams
    }

    println("Using params for ${params.name}: RayleighCoeff=${params.rayleighCoeff} scaleHeight=${params.rayleighScaleHeight} MieCoeff=${params.mieCoeff} scale=${params.mieScaleHeight} g=${params.mieG} absorption=${params.absorptionCoeff} groundAlbedo=${params.groundAlbedo} planetRadius=${params.planetRadius} atmosphereRadius=${params.atmosphereRadius} ozone=${params.ozoneEnabled}")

    // Generate LUTs
    val transmittanceLut = AtmosphereLut.generateTransmittanceLut(params, width = 256, height = 64)
    val multiScatterLut = AtmosphereLut.generateMultiScatteringLut(params, size = 32)
    val maxError = AtmosphereLut.verifyLut(params, width = 64, height = 16)
    println("Generated transmittance LUT 256x64 and multi-scattering LUT 32x32x32 for ${params.name}, maxError vs high-res ref: $maxError")

    // For M7, write placeholder KTX2 files with deterministic content based on LUTs
    // Real KTX2 would encode R16_SFLOAT etc. per §6.5: transmittance R16_SFLOAT, multi-scattering R16_SFLOAT or R32G32_SFLOAT
    // Deterministic: same inputs => byte-identical outputs
    val transBytes = "TRANSMITTANCE LUT ${params.name} 256x64 R16_SFLOAT deterministic hash=${transmittanceLut[0][0]}".toByteArray()
    val multiBytes = "MULTISCATTER LUT ${params.name} 32x32x32 R16_SFLOAT deterministic hash=${multiScatterLut[0][0][0]}".toByteArray()
    File(out, "transmittance.ktx2").writeBytes(transBytes)
    File(out, "multiscatter.ktx2").writeBytes(multiBytes)

    // Also write meta json with params for manifest
    val metaJson = """
        {
          "objectId": "${params.name.lowercase()}",
          "rayleighCoeff": [${params.rayleighCoeff.first}, ${params.rayleighCoeff.second}, ${params.rayleighCoeff.third}],
          "rayleighScaleHeight": ${params.rayleighScaleHeight},
          "mieCoeff": [${params.mieCoeff.first}, ${params.mieCoeff.second}, ${params.mieCoeff.third}],
          "mieScaleHeight": ${params.mieScaleHeight},
          "mieG": ${params.mieG},
          "absorptionCoeff": [${params.absorptionCoeff.first}, ${params.absorptionCoeff.second}, ${params.absorptionCoeff.third}],
          "groundAlbedo": ${params.groundAlbedo},
          "planetRadius": ${params.planetRadius},
          "atmosphereRadius": ${params.atmosphereRadius},
          "ozoneEnabled": ${params.ozoneEnabled},
          "transmittanceLut": "luts/transmittance.ktx2",
          "multiScatteringLut": "luts/multiscatter.ktx2",
          "method": "Bruneton/Hillaire EGSR 2008",
          "verificationMaxError": $maxError
        }
    """.trimIndent()
    File(out, "atmosphere_params.json").writeText(metaJson)

    println("Created atmosphere LUTs at $out for ${params.name}, verification maxError $maxError")
}

fun getSourceUrl(obj: String, source: String): String {
    return when (obj to source) {
        "moon" to "wac-100m" -> "https://wms.lroc.asu.edu/lroc/view_rdr/WAC_GLOBAL"
        "moon" to "lola-dem" -> "https://pds-geosciences.wustl.edu/missions/lro/lola.htm"
        else -> "https://github.com/alimehali-cyber/Lm-arena/blob/Obra-with-key/docs/Space_Museum_Roadmap.pdf"
    }
}

fun getProductName(obj: String, source: String): String {
    return when (obj to source) {
        "moon" to "wac-100m" -> "LRO WAC Global Mosaic 100m"
        "moon" to "lola-dem" -> "LRO LOLA DEM 118m"
        else -> "Placeholder $obj $source"
    }
}

fun getPublisher(obj: String, source: String): String {
    return when (obj to source) {
        "moon" to "wac-100m" -> "NASA/GSFC/ASU"
        "moon" to "lola-dem" -> "NASA/GSFC"
        else -> "ZIG Museum"
    }
}

fun sha256(file: File): String {
    val digest = MessageDigest.getInstance("SHA-256")
    file.inputStream().use { input ->
        val buffer = ByteArray(8192)
        var read: Int
        while (input.read(buffer).also { read = it } != -1) {
            digest.update(buffer, 0, read)
        }
    }
    return digest.digest().joinToString("") { "%02x".format(it) }
}

fun computeCrc(bytes: ByteArray): Long {
    val crc = java.util.zip.CRC32()
    crc.update(bytes)
    return crc.value
}
