package com.alijafari.red.astronomy

import com.alijafari.red.astronomy.astro_engine.AstroTime
import com.alijafari.red.astronomy.astro_engine.CoordinateEngine
import com.alijafari.red.astronomy.astro_engine.MoonEngine
import com.alijafari.red.astronomy.astro_engine.PlanetEngine
import com.alijafari.red.astronomy.astro_engine.SunEngine
import com.alijafari.red.astronomy.astro_engine.TimeEngine
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File
import kotlin.math.*

/**
 * F-A permanent oracle test (final pass, item A5). Pins the LIVE coordinate chain to the
 * astropy oracle captured in docs/startracker/evidence/ORACLE_CASES*.csv (generated by
 * tools/oracle/astropy_oracle.py driving astropy 8.0.1, IERS offline, builtin ephemeris,
 * on the deterministic A2 grid: 6 locations x 6 instants 2000-2030).
 *
 * Oracle columns were produced INDEPENDENTLY of this project's code. This test RECOMPUTES
 * the live routes through the real engines (same call sequence as CompassARScreen /
 * AstroDispatchEngine) and asserts on-sky separation vs the oracle refraction column:
 *   stars/DSO < 2.0', sun < 1.0', moon < 3.0', planets < 2.0'   (alt > 10 deg only)
 *
 * Fixes pinned by this test (F-A "KIND-B"):
 *  - star precession: J2000 catalog coords must pass precessJ2000EquatorialToDate
 *    (pre-fix bug: raw J2000 fed to of-date LAST -> ~17.5' error in 2026, ~20' by 2030)
 *  - ΔT: genuine Espenak-Meeus piecewise (pre-fix invented cubic gave 96.3s in 2026)
 *  - VSOP87 tables regenerated from VSOP87D (pre-fix hand-mangled tables: planets off
 *    by arcminutes-to-degrees)
 *
 * Mutation proof (G2): run against the pre-fix worktree — fails (star ~17.5', sun ~5',
 * planets degrees-scale). Pasted failure in the commit body.
 */
class CoordinateOracleTest {

    // A2 grid (must match tools/oracle/astropy_oracle.py + CoordinateOracleProbe.kt)
    private val locs = mapOf(
        "Tehran" to Triple(35.69, 51.39, 1200.0),
        "Sydney" to Triple(-33.87, 151.21, 40.0),
        "Quito" to Triple(0.0, -78.5, 2850.0),
        "Tromso" to Triple(69.65, 18.96, 10.0),
        "CapeTown" to Triple(-33.93, 18.42, 25.0),
        "Honolulu" to Triple(21.31, -157.86, 5.0)
    )

    private fun parseIso(iso: String): AstroTime {
        // "2026-09-04T20:00:00"
        val d = iso.substring(0, 10).split("-").map { it.toInt() }
        val t = iso.substring(11).split(":").map { it.toInt() }
        return AstroTime.fromUtcDate(d[0], d[1], d[2], t[0], t[1], t.getOrElse(2) { 0 })
    }

    private fun loadCsv(name: String): List<Map<String, String>> {
        val candidates = listOf(
            "app/src/test/resources/startracker/$name", // repo root cwd (offline harness)
            "src/test/resources/startracker/$name"      // Gradle test cwd (app/)
        )
        val f = candidates.map(::File).firstOrNull { it.exists() }
            ?: throw AssertionError("oracle CSV not found: $name (cwd=${File(".").absolutePath})")
        val lines = f.readLines().filter { it.isNotBlank() }
        val hdr = lines.first().split(",").map { it.trim() }
        return lines.drop(1).map { l -> hdr.zip(l.split(",").map { it.trim() }).toMap() }
    }

    private fun sepArcmin(az1: Double, alt1: Double, az2: Double, alt2: Double): Double {
        val a1 = Math.toRadians(az1); val l1 = Math.toRadians(alt1)
        val a2 = Math.toRadians(az2); val l2 = Math.toRadians(alt2)
        val cd = (sin(l1) * sin(l2) + cos(l1) * cos(l2) * cos(a1 - a2)).coerceIn(-1.0, 1.0)
        return Math.toDegrees(acos(cd)) * 60.0
    }

    private fun astroTimeAt(r: Map<String, String>): AstroTime {
        val (lat, lon, _) = locs[r["loc"]] ?: error("unknown loc ${r["loc"]}")
        return parseIso(r["iso_utc"]!!)
    }

    /** Star route: exact live sequence from CompassARScreen (fixed in F-A5). */
    private fun starLive(r: Map<String, String>): Pair<Double, Double> {
        val (lat, lon, _) = locs[r["loc"]]!!
        val at = parseIso(r["iso_utc"]!!)
        val jd = TimeEngine.getJulianDate(at.utcMs)
        val last = TimeEngine.getLAST(jd, lon)
        val eq = CoordinateEngine.precessJ2000EquatorialToDate(
            r["ra_in_deg"]!!.toDouble(), r["dec_in_deg"]!!.toDouble(), jd
        )
        val hz = CoordinateEngine.equatorialToHorizontal(eq, last, lat)
        return hz.azimuthDeg to hz.altitudeDeg
    }

    @Test
    fun testStarRouteAgainstOracle() {
        val rows = loadCsv("ORACLE_CASES.csv")
        assertTrue("expected >= 300 oracle star rows, got ${rows.size}", rows.size >= 300)
        val ds = ArrayList<Double>()
        rows.forEach { r ->
            val altO = r["alt_oracle_refr_appweather"]!!.toDouble()
            if (altO <= 10.0) return@forEach
            val (az, alt) = starLive(r)
            ds += sepArcmin(az, alt, r["az_oracle_refr_appweather"]!!.toDouble(), altO)
        }
        assertTrue("expected >= 30 star cells above 10 deg, got ${ds.size}", ds.size >= 30)
        val max = ds.max(); val rms = sqrt(ds.map { it * it }.average())
        assertTrue(
            "star_live recomputed vs astropy(app-weather refr): max=${"%.3f".format(max)}' rms=${"%.3f".format(rms)}' " +
                "exceeds 2.0' (pre-fix baseline ~17.5' median 2026 — evidence/ORACLE_RESIDUALS_BEFORE_FIX.txt)",
            max <= 2.0
        )
    }

    @Test
    fun testBodiesAgainstOracle() {
        val rows = loadCsv("ORACLE_CASES_BODIES.csv")
        val limits = mapOf("sun" to 1.0, "moon" to 3.0)
        val worst = HashMap<String, Double>()
        rows.forEach { r ->
            val route = r["route"]!!
            if (route == "moon_geocentric") return@forEach  // diagnostic-only route (parallax check), not live path
            val (lat, lon, h) = locs[r["loc"]]!!
            val altO = r["alt_oracle_refr_appweather"]!!.toDouble()
            if (altO <= 10.0) return@forEach
            val at = parseIso(r["iso_utc"]!!)
            val jd = TimeEngine.getJulianDate(at.utcMs)
            val last = TimeEngine.getLAST(jd, lon)
            val hz: Pair<Double, Double> = when (route) {
                "sun" -> SunEngine.getSunAltAz(jd, lat, lon).let { it.azimuthDeg to it.altitudeDeg }
                "moon" -> MoonEngine.calculateMoon(jd = jd, latitude = lat, longitude = lon, elevationM = h).let { it.azimuthDeg to it.altitudeDeg }
                else -> {
                    val p = PlanetEngine.PlanetType.valueOf(route.removePrefix("planet_").uppercase())
                    val pos = PlanetEngine.calculatePlanet(p, at)
                    CoordinateEngine.equatorialToHorizontal(CoordinateEngine.Equatorial(pos.raDeg, pos.decDeg), last, lat).let { it.azimuthDeg to it.altitudeDeg }
                }
            }
            val d = sepArcmin(hz.first, hz.second, r["az_oracle_refr_appweather"]!!.toDouble(), altO)
            worst[route] = maxOf(worst[route] ?: 0.0, d)
            val lim = limits[route] ?: 2.0
            assertTrue("$route at ${r["loc"]}/${r["iso_utc"]}: $d' exceeds ${lim}'", d <= lim)
        }
        listOf("sun", "moon", "planet_mars", "planet_venus").forEach { route ->
            assertTrue("no cells above horizon for $route", route in worst)
        }
    }

    @Test
    fun testDeltaTModernEra() {
        // F-A5: ΔT(2026) must be the genuine Espenak-Meeus value, not the invented cubic
        // (pre-fix: 96.3s; real IERS ≈ 69.4s; EM 2005-2050 piecewise ≈ 75.9s).
        val at = AstroTime.fromUtcDate(2026, 9, 4, 20, 0, 0)
        val dt = at.deltaT
        assertTrue("ΔT(2026) = ${dt}s, expected ≈69-76s (pre-fix bug gave 96.3s)", dt in 65.0..78.0)
    }
}
