package com.alijafari.red.astronomy.startracker.calibration

import org.junit.Test
import org.junit.Assert.*
import kotlin.math.*

class DistortionModelTest {

    @Test
    fun testNoDistortionRoundTrip() {
        val model = DistortionModel.noDistortion()

        val points = listOf(
            Pair(0.0, 0.0),
            Pair(0.1, 0.1),
            Pair(-0.2, 0.3),
            Pair(0.5, 0.5),
            Pair(-0.5, -0.5)
        )

        for ((x, y) in points) {
            val (xDist, yDist) = model.distortIdealToDistortedNormalized(x, y)
            assertEquals(x, xDist, 1e-9)
            assertEquals(y, yDist, 1e-9)

            val (xUndist, yUndist) = model.undistortDistortedToIdealNormalized(xDist, yDist)
            assertEquals(x, xUndist, 1e-9)
            assertEquals(y, yUndist, 1e-9)
        }
    }

    @Test
    fun testRoundTripWithDistortion() {
        val testCases = listOf(
            DistortionModel(k1 = 0.1, k2 = 0.01, p1 = 0.001, p2 = 0.001), // mild
            DistortionModel(k1 = 0.2, k2 = 0.05, p1 = 0.01, p2 = 0.01), // moderate
            DistortionModel(k1 = -0.3, k2 = 0.1, p1 = -0.01, p2 = 0.01) // strong wide-angle-like (negative k1)
        )

        val points = listOf(
            Pair(0.0, 0.0), // center
            Pair(0.1, 0.1),
            Pair(0.3, 0.2), // edge
            Pair(0.5, 0.5), // corner
            Pair(-0.4, 0.3)
        )

        println("Round-trip distortion error:")
        println("Distortion | Point | distort->undistort error | undistort->distort error")
        for (model in testCases) {
            for ((x, y) in points) {
                // distort then undistort
                val (xDist, yDist) = model.distortIdealToDistortedNormalized(x, y)
                val (xUndist, yUndist) = model.undistortDistortedToIdealNormalized(xDist, yDist)
                val err1 = hypot(x - xUndist, y - yUndist)

                // undistort then distort (starting from distorted)
                val (xIdeal2, yIdeal2) = model.undistortDistortedToIdealNormalized(x, y)
                val (xDist2, yDist2) = model.distortIdealToDistortedNormalized(xIdeal2, yIdeal2)
                val err2 = hypot(x - xDist2, y - yDist2)

                println("k1=${model.k1},k2=${model.k2} | ($x,$y) | err1=${"%.2e".format(err1)} | err2=${"%.2e".format(err2)}")

                assertTrue("Round-trip distort->undistort error should be <1e-6, got $err1", err1 < 1e-6)
                assertTrue("Round-trip undistort->distort error should be <1e-6, got $err2", err2 < 1e-6)
            }
        }
    }

    @Test
    fun testPixelRoundTrip() {
        val model = DistortionModel(k1 = 0.1, k2 = 0.01, p1 = 0.001, p2 = 0.001)
        val fx = 1000.0
        val fy = 1000.0
        val cx = 960.0
        val cy = 540.0

        val pixels = listOf(
            Pair(cx, cy), // center
            Pair(100.0, 100.0), // corner
            Pair(1820.0, 980.0), // opposite corner
            Pair(960.0, 100.0) // edge
        )

        for ((u, v) in pixels) {
            val (uDist, vDist) = model.distortPixel(u, v, fx, fy, cx, cy)
            val (uUndist, vUndist) = model.undistortPixel(uDist, vDist, fx, fy, cx, cy)
            val err = hypot(u - uUndist, v - vUndist)
            println("Pixel ($u,$v) -> distorted ($uDist,$vDist) -> undistorted ($uUndist,$vUndist), err $err")
            assertTrue("Pixel round-trip error <1e-3", err < 1e-3)
        }
    }

    @Test
    fun testPythonCrossCheck() {
        // REAL Python cross-check (audit remediation): the previous version carried
        // hardcoded "expected from Python (approx)" values that were never asserted
        // (it only checked isFinite) - and they were WRONG: it claimed (0.100405, 0.20081)
        // for input (0.1, 0.2) where the true Brown-Conrady output is (0.100495, 0.201540).
        // The expected values below were generated by an independent CPython 3 execution
        // (python3, double precision) of the textbook formula:
        //   x' = x(1 + k1 r^2 + k2 r^4) + 2 p1 x y + p2 (r^2 + 2 x^2)
        //   y' = y(1 + k1 r^2 + k2 r^4) + p1 (r^2 + 2 y^2) + 2 p2 x y
        val model = DistortionModel(k1 = 0.1, k2 = 0.02, p1 = 0.005, p2 = -0.003)

        val expectedFromPython = listOf(
            Triple(0.1, 0.2, Pair(0.10049500000000001, 0.20154000000000002)),
            Triple(0.3, -0.2, Pair(0.30247139999999995, -0.20125759999999998)),
            Triple(0.0, 0.0, Pair(0.0, 0.0)),
            Triple(0.7, 0.5, Pair(0.7578064, 0.5465760000000001)),
            Triple(-0.4, 0.6, Pair(-0.42788320000000013, 0.6420848))
        )

        for ((x, y, pyExpected) in expectedFromPython) {
            val (xDist, yDist) = model.distortIdealToDistortedNormalized(x, y)
            assertEquals("Python-vs-Kotlin x for input ($x, $y)", pyExpected.first, xDist, 1e-15)
            assertEquals("Python-vs-Kotlin y for input ($x, $y)", pyExpected.second, yDist, 1e-15)
            println("Python cross-check: ideal ($x,$y) -> distorted ($xDist,$yDist) == python " +
                "(" + pyExpected.first + "," + pyExpected.second + ")")
        }
    }
}
